[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_version = "20"

# Redirects (equivalent to the ones in astro.config.mjs)
[[redirects]]
  from = "/scherminitiatie"
  to = "/teambuildings/indoor-scherminitiatie"
  status = 302

[[redirects]]
  from = "/roofvogelworkshop"
  to = "/teambuildings/roofvogelworkshop"
  status = 302

[[redirects]]
  from = "/djembe"
  to = "/teambuildings/djembe"
  status = 302

[[redirects]]
  from = "/sumoworstelen"
  to = "/teambuildings/indoor-sumoworstelen"
  status = 302

[[redirects]]
  from = "/laserkleiduifschieten"
  to = "/teambuildings/laserkleiduifschieten"
  status = 302

[[redirects]]
  from = "/bijlwerpen"
  to = "/teambuildings/bijlwerpen"
  status = 302

[[redirects]]
  from = "/biathlonschieten"
  to = "/teambuildings/indoor-laser-karabijn"
  status = 302

[[redirects]]
  from = "/boogschieten"
  to = "/teambuildings/boogschieten"
  status = 302

[[redirects]]
  from = "/smaaktest"
  to = "/teambuildings/smaaktest"
  status = 302

[[redirects]]
  from = "/kunstsmeden"
  to = "/teambuildings/kunstsmeden"
  status = 302

[[redirects]]
  from = "/pistoolschieten"
  to = "/teambuildings/luchtdruk-pistoolschieten"
  status = 302