import { useTranslations } from '@/i18n/utils';

interface FooterLink {
  id: string;
  url: string;
}

interface FooterSection {
  title: string;
  links: FooterLink[];
}

export const footerLinks: FooterSection[] = [
  {
    title: 'footer.sections.indoor',
    links: [
      { id: 'scherminitiatie', url: '/teambuildings/scherminitiatie' },
      { id: 'mobiele-escape-room', url: '/teambuildings/mobiele-escape-room' },
      { id: 'dronevliegen', url: '/teambuildings/dronevliegen' },
      { id: 'virtual-reality', url: '/teambuildings/virtual-reality' },
      { id: 'laser-biatlon', url: '/teambuildings/laser-biatlon' },
      { id: 'laserschermen', url: '/teambuildings/laserschermen' },
      { id: 'arrowtag', url: '/teambuildings/arrowtag' },
      { id: 'smaaktest', url: '/teambuildings/smaaktest' },
      { id: 'chocoladeworkshop', url: '/teambuildings/chocoladeworkshop' },
      { id: 'sumoworstelen', url: '/teambuildings/sumoworstelen' },
      { id: 'blaaspijpschieten', url: '/teambuildings/blaaspijpschieten' },
      { id: 'volksspelen', url: '/teambuildings/volksspelen' },
      { id: 'djembe', url: '/teambuildings/djembe' },
      { id: 'indoor-lasershooting', url: '/teambuildings/indoor-lasershooting' },
      { id: 'mollenjacht', url: '/teambuildings/mollenjacht' },
      { id: 'moorddiner', url: '/teambuildings/moorddiner' },
      { id: 'chain-reaction', url: '/teambuildings/chain-reaction' },
      { id: 'groupo-universalis', url: '/teambuildings/groupo-universalis' },
      { id: 'moord-mystery', url: '/teambuildings/moord-mystery' },
      { id: 'innovation-games', url: '/teambuildings/innovation-games' },
      { id: 'de-anderen', url: '/teambuildings/de-anderen' },
      { id: 'office-games', url: '/teambuildings/office-games' },
      { id: 'space-games', url: '/teambuildings/space-games' },
      { id: 'spy-academy', url: '/teambuildings/spy-academy' },
      { id: 'teambooster', url: '/teambuildings/teambooster' },
      { id: 'voetbalmanie', url: '/teambuildings/voetbalmanie' },
    ],
  },
  {
    title: 'footer.sections.outdoor',
    links: [
      { id: 'scherminitiatie', url: '/teambuildings/scherminitiatie' },
      { id: 'mobiele-escape-room', url: '/teambuildings/mobiele-escape-room' },
      { id: 'laser-kleiduifschieten', url: '/teambuildings/laser-kleiduifschieten' },
      { id: 'dronevliegen', url: '/teambuildings/dronevliegen' },
      { id: 'bijlwerpen', url: '/teambuildings/bijlwerpen' },
      { id: 'laser-biatlon', url: '/teambuildings/laser-biatlon' },
      { id: 'kunstsmeden', url: '/teambuildings/kunstsmeden' },
      { id: 'laser-schermen', url: '/teambuildings/laser-schermen' },
      { id: 'arrowtag', url: '/teambuildings/arrowtag' },
      { id: 'gelblaster', url: '/teambuildings/gelblaster' },
      { id: 'roofvogelworkshop', url: '/teambuildings/roofvogelworkshop' },
      { id: 'sumoworstelen', url: '/teambuildings/sumoworstelen' },
      { id: 'boogschieten', url: '/teambuildings/boogschieten' },
      { id: 'blaaspijpschieten', url: '/teambuildings/blaaspijpschieten' },
      { id: 'volksspelen', url: '/teambuildings/volksspelen' },
      { id: 'djembe', url: '/teambuildings/djembe' },
      { id: 'pistoolschieten', url: '/teambuildings/pistoolschieten' },
      { id: 'vuurlopen', url: '/teambuildings/vuurlopen' },
      { id: 'alpacaworkshop', url: '/teambuildings/alpacaworkshop' },
      { id: 'molenjacht', url: '/teambuildings/molenjacht' },
      { id: 'highland-games', url: '/teambuildings/highland-games' },
      { id: 'expeditie-robinson', url: '/teambuildings/expeditie-robinson' },
      { id: 'groupo-universalis', url: '/teambuildings/groupo-universalis' },
      { id: 'teambooster', url: '/teambuildings/teambooster' },
      { id: 'excalibur', url: '/teambuildings/excalibur' },
      { id: 'funny-olympic-games', url: '/teambuildings/funny-olympic-games' },
      { id: 'de-anderen', url: '/teambuildings/de-anderen' },
      { id: 'middeleeuws-dag', url: '/teambuildings/middeleeuws-dag' },
      { id: 'spy-academy', url: '/teambuildings/spy-academy' },
      { id: 'zweedse-games', url: '/teambuildings/zweedse-games' },
      { id: 'voetbalmanie', url: '/teambuildings/voetbalmanie' },
    ],
  },
  {
    title: 'footer.sections.actief',
    links: [
      { id: 'scherminitiatie', url: '/teambuildings/scherminitiatie' },
      { id: 'laser-schermen', url: '/teambuildings/laser-schermen' },
      { id: 'kunstsmeden', url: '/teambuildings/kunstsmeden' },
      { id: 'arrowtag', url: '/teambuildings/arrowtag' },
      { id: 'gelblaster', url: '/teambuildings/gelblaster' },
      { id: 'sumoworstelen', url: '/teambuildings/sumoworstelen' },
      { id: 'highland-games', url: '/teambuildings/highland-games' },
      { id: 'funny-olympic-games', url: '/teambuildings/funny-olympic-games' },
      { id: 'expeditie-robinson', url: '/teambuildings/expeditie-robinson' },
      { id: 'fort-boyard', url: '/teambuildings/fort-boyard' },
      { id: 'excalibur', url: '/teambuildings/excalibur' },
      { id: 'zweedse-games', url: '/teambuildings/zweedse-games' },
      { id: 'middeleeuws-dag', url: '/teambuildings/middeleeuws-dag' },
    ],
  },
  {
    title: 'footer.sections.innovaction',
    links: [
      { id: 'laser-schermen', url: '/teambuildings/laser-schermen' },
      { id: 'dronevliegen', url: '/teambuildings/dronevliegen' },
      { id: 'laser-kleiduifschieten', url: '/teambuildings/laser-kleiduifschieten' },
      { id: 'virtual-reality', url: '/teambuildings/virtual-reality' },
      { id: 'laser-biatlon', url: '/teambuildings/laser-biatlon' },
      { id: 'mobiele-escape-room', url: '/teambuildings/mobiele-escape-room' },
      { id: 'gelblaster', url: '/teambuildings/gelblaster' },
      { id: 'indoor-lasershooting', url: '/teambuildings/indoor-lasershooting' },
      { id: 'innovation-games', url: '/teambuildings/innovation-games' },
      { id: 'space-games', url: '/teambuildings/space-games' },
      { id: 'spy-academy', url: '/teambuildings/spy-academy' },
    ],
  },
  {
    title: 'footer.sections.city-games',
    links: [
      { id: 'brugse-metten-tocht', url: '/teambuildings/brugse-metten-tocht' },
      { id: 'antwerpse-straffe-handjes', url: '/teambuildings/antwerpse-straffe-handjes' },
      { id: 'gentse-stroppentocht', url: '/teambuildings/gentse-stroppentocht' },
    ],
  },
  {
    title: 'footer.sections.workshops',
    links: [
      { id: 'smaaktest', url: '/teambuildings/smaaktest' },
      { id: 'chocoladeworkshop', url: '/teambuildings/chocoladeworkshop' },
      { id: 'kunstsmeden', url: '/teambuildings/kunstsmeden' },
      { id: 'vuurlopen', url: '/teambuildings/vuurlopen' },
      { id: 'roofvogelworkshop', url: '/teambuildings/roofvogelworkshop' },
      { id: 'djembe', url: '/teambuildings/djembe' },
      { id: 'alpacaworkshop', url: '/teambuildings/alpacaworkshop' },
    ],
  },
];
